package Authorization;

import org.testng.annotations.Test;

import io.restassured.RestAssured;

import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

public class APIKeyAuthorization {

	// Key is generated by server and given to client
	// client then sends the key along with each request to server and server use it
	// to identify the user to authorize

	// https://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}

	@Test
	public void getWeatherDataByCity() {
		RequestSpecification requestSpec = RestAssured.given();

		// specify base uri
		requestSpec.baseUri("https://api.openweathermap.org");
		requestSpec.basePath("/data/2.5/weather");

		// API key will be generated or received by site else sign on above site url
		requestSpec.queryParams("q", "delhi").queryParam("appid", "858hfuy48ryhfuy4854");
		Response response = requestSpec.get();

		System.out.println("Response status line od API Key is " + response.getStatusLine());
		System.out.println("Response body of API Key is " + response.body().asString());

	}

}
